In [1]:
import numpy as np 

import pandas as pd 

import matplotlib.pyplot as plt 

df = pd.read_excel("../datasets/Sample - Superstore.xls") 

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [4]:
df.sample(n=5)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
3852,3853,CA-2017-130526,2017-11-26,2017-11-29,First Class,GT-14755,Guy Thornton,Consumer,United States,Rockford,...,61107,Central,OFF-BI-10001524,Office Supplies,Binders,GBC Premium Transparent Covers with Diagonal L...,33.568,8,0.8,-53.7088
1602,1603,US-2016-132857,2016-12-11,2016-12-17,Standard Class,CA-12775,Cynthia Arntzen,Consumer,United States,Smyrna,...,37167,South,OFF-AR-10003251,Office Supplies,Art,Prang Drawing Pencil Set,6.672,3,0.2,1.6680
5355,5356,CA-2014-113768,2014-05-13,2014-05-19,Standard Class,AH-10030,Aaron Hawkins,Corporate,United States,Los Angeles,...,90004,West,OFF-PA-10003063,Office Supplies,Paper,EcoTones Memo Sheets,8.000,2,0.0,3.8400
9844,9845,CA-2014-163867,2014-06-03,2014-06-06,First Class,RE-19450,Richard Eichhorn,Consumer,United States,Decatur,...,62521,Central,FUR-FU-10001475,Furniture,Furnishings,"Contract Clock, 14"", Brown",61.544,7,0.6,-40.0036
9709,9710,CA-2016-161746,2016-10-21,2016-10-27,Standard Class,CS-11950,Carlos Soltero,Consumer,United States,Los Angeles,...,90045,West,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,340.920,3,0.0,3.4092

In [5]:
df.sample(frac=0.1)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
5132,5133,CA-2015-123330,2015-06-21,2015-06-27,Standard Class,EP-13915,Emily Phan,Consumer,United States,Deltona,...,32725,South,TEC-PH-10001819,Technology,Phones,Innergie mMini Combo Duo USB Travel Charging Kit,107.976,3,0.2,37.7916
3609,3610,CA-2014-140228,2014-04-28,2014-05-03,Standard Class,GB-14530,George Bell,Corporate,United States,Newark,...,43055,East,OFF-ST-10002214,Office Supplies,Storage,X-Rack File for Hanging Folders,27.096,3,0.2,2.0322
2304,2305,CA-2017-157931,2017-09-17,2017-09-22,Second Class,MO-17800,Meg O'Connel,Home Office,United States,Roswell,...,30076,South,OFF-PA-10000474,Office Supplies,Paper,Easy-staple paper,106.320,3,0.0,49.9704
4718,4719,CA-2015-109736,2015-10-10,2015-10-11,First Class,DJ-13420,Denny Joy,Corporate,United States,San Francisco,...,94109,West,OFF-PA-10004101,Office Supplies,Paper,Xerox 1894,45.360,7,0.0,21.7728
5023,5024,CA-2016-133795,2016-12-18,2016-12-24,Standard Class,JE-15475,Jeremy Ellison,Consumer,United States,San Diego,...,92037,West,FUR-FU-10003731,Furniture,Furnishings,Eldon Expressions Wood and Plastic Desk Access...,39.920,4,0.0,11.1776
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4156,4157,CA-2015-101091,2015-12-05,2015-12-09,Second Class,SW-20245,Scot Wooten,Consumer,United States,Philadelphia,...,19140,East,TEC-AC-10003280,Technology,Accessories,Belkin F8E887 USB Wired Ergonomic Keyboard,47.984,2,0.2,0.5998
2641,2642,CA-2015-169740,2015-02-20,2015-02-25,Standard Class,LM-17065,Liz MacKendrick,Consumer,United States,Hot Springs,...,71901,South,TEC-AC-10000927,Technology,Accessories,Anker Ultrathin Bluetooth Wireless Keyboard Al...,29.990,1,0.0,2.9990
3874,3875,CA-2016-136231,2016-09-05,2016-09-07,Second Class,DM-13015,Darrin Martin,Consumer,United States,Johnson City,...,37604,South,OFF-BI-10001597,Office Supplies,Binders,"Wilson Jones Ledger-Size, Piano-Hinge Binder, ...",86.058,7,0.7,-63.1092
4193,4194,CA-2015-150875,2015-11-16,2015-11-20,Standard Class,HK-14890,Heather Kirkland,Corporate,United States,Boise,...,83704,West,TEC-PH-10001254,Technology,Phones,Jabra BIZ 2300 Duo QD Duo Corded Headset,304.776,3,0.2,22.8582
3566,3567,CA-2017-103877,2017-09-07,2017-09-14,Standard Class,RD-19660,Robert Dilbeck,Home Office,United States,Independence,...,64055,Central,OFF-BI-10003650,Office Supplies,Binders,GBC DocuBind 300 Electric Binding Machine,1577.940,3,0.0,757.4112

In [8]:
df.sample(frac=0.1, replace=True)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
3548,3549,CA-2017-155292,2017-10-30,2017-11-01,First Class,RD-19810,Ross DeVincentis,Home Office,United States,Richmond,...,40475,South,FUR-CH-10000553,Furniture,Chairs,"Metal Folding Chairs, Beige, 4/Carton",33.94,1,0.0,9.1638
6420,6421,CA-2016-140130,2016-10-31,2016-11-05,Standard Class,HW-14935,Helen Wasserman,Corporate,United States,Tulsa,...,74133,Central,OFF-AR-10004269,Office Supplies,Art,Newell 31,12.39,3,0.0,3.4692
4599,4600,CA-2015-146948,2015-07-16,2015-07-20,Standard Class,MG-17890,Michael Granlund,Home Office,United States,Baltimore,...,21215,East,FUR-CH-10004853,Furniture,Chairs,"Global Manager's Adjustable Task Chair, Storm",150.98,1,0.0,43.7842
5581,5582,CA-2017-163818,2017-10-04,2017-10-08,Standard Class,PS-18970,Paul Stevenson,Home Office,United States,Clinton,...,20735,East,FUR-FU-10000076,Furniture,Furnishings,24-Hour Round Wall Clock,19.98,1,0.0,8.5914
593,594,CA-2014-135405,2014-01-09,2014-01-13,Standard Class,MS-17830,Melanie Seite,Consumer,United States,Laredo,...,78041,Central,TEC-AC-10001266,Technology,Accessories,Memorex Micro Travel Drive 8 GB,31.20,3,0.2,9.7500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5525,5526,CA-2017-154501,2017-04-30,2017-05-05,Standard Class,EA-14035,Erin Ashbrook,Corporate,United States,Los Angeles,...,90008,West,OFF-AR-10002804,Office Supplies,Art,Faber Castell Col-Erase Pencils,9.78,2,0.0,4.0098
525,526,CA-2015-158792,2015-12-26,2016-01-02,Standard Class,BD-11605,Brian Dahlen,Consumer,United States,Lawrence,...,1841,East,OFF-FA-10002815,Office Supplies,Fasteners,Staples,22.20,5,0.0,10.4340
5585,5586,CA-2017-105333,2017-11-30,2017-12-04,Standard Class,VP-21730,Victor Preis,Home Office,United States,New York City,...,10011,East,TEC-PH-10001468,Technology,Phones,Panasonic Business Telephones KX-T7736,546.06,3,0.0,163.8180
2253,2254,CA-2015-169201,2015-09-28,2015-10-01,First Class,HG-14965,Henry Goldwyn,Corporate,United States,San Francisco,...,94110,West,OFF-AP-10000696,Office Supplies,Appliances,Holmes Odor Grabber,43.26,3,0.0,14.2758
8015,8016,CA-2017-120168,2017-05-25,2017-05-25,Same Day,TB-21625,Trudy Brown,Consumer,United States,New York City,...,10009,East,FUR-FU-10000732,Furniture,Furnishings,Eldon 200 Class Desk Accessories,18.84,3,0.0,6.0288