
*  DSC530-T302 Data Exploration and Analysis (2263-1)
*  Weeks 5 & 6 Coding Assignment
*  Paula Iman

# Chapter 4, Exercises 1, 2, 4, 6, 7, and 10, in Hands-On Data Analysis with Pandas (Molin, 2021)

#Exercise 1.

With the earthquakes.csv file, select all the earthquakes in Japan with a magnitude of 4.9 or greater using the mb magnitude type.

In [55]:
import numpy as np
import pandas as pd

earthquakes = pd.read_csv('earthquakes.csv')

earthquakes.head() #checked for headings in data

    mag magType           time                  place  tsunami parsed_place
0  1.35      ml  1539475168010  9km NE of Aguanga, CA        0   California
1  1.29      ml  1539475129610  9km NE of Aguanga, CA        0   California
2  3.42      ml  1539475062610  8km NE of Aguanga, CA        0   California
3  0.44      ml  1539474978070  9km NE of Aguanga, CA        0   California
4  2.16      md  1539474716050  10km NW of Avenal, CA        0   California

In [56]:
#Choosing earthquakes where the place equals 'Japan,' and the magnitude is 4.9 or bigger, and where mag type is 'mb'
japan_mb_earthquakes = earthquakes[(earthquakes.parsed_place == 'Japan') & (earthquakes.mag >= 4.9) & (earthquakes.magType =='mb')]
japan_mb_earthquakes

,mag,magType,time,place,tsunami,parsed_place
1563,4.9,mb,1538977532250,"293km ESE of Iwo Jima, Japan",0,Japan
2576,5.4,mb,1538697528010,"37km E of Tomakomai, Japan",0,Japan
3072,4.9,mb,1538579732490,"15km ENE of Hasaki, Japan",0,Japan
3632,4.9,mb,1538450871260,"53km ESE of Hitachi, Japan",0,Japan

Exercise 2.

Create bins for each full number of earthquake magnitude (for instance, the first bin is (0,1], the second is (1,2], and so on) with the ml magnitude type and count how many are in each bin.

In [57]:
#selecting earthquakes with magType ml
ml_earthquakes = earthquakes[earthquakes.magType == 'ml']

#finding the maximum mag value using np.ceil(), assigning it as int
mag_max = int(np.ceil(ml_earthquakes.mag.max()))

#creating a list for bins where the largest value is included
bins = list(range(0, mag_max +1))

#using pd.cut to assign the values in bins starting from (0,1] (including 1)
binned_ml_counts = pd.cut(ml_earthquakes.mag, bins = bins).value_counts().sort_index()

#printing out the result
print(binned_ml_counts)

mag
(0, 1]    2207
(1, 2]    3105
(2, 3]     862
(3, 4]     122
(4, 5]       2
(5, 6]       1
Name: count, dtype: int64

Exercise 4.

Build a crosstab with the earthquake data between the tsunami column and the magType column. Rather than showing the frequency count, show the maximum magnitude that was observed for each combination. Put the magnitude type along the columns.

In [58]:
#using crosstab() using tsunami as rows and magType as columns
#aggfunc='max' finds the largest magnitude of earthquakes
mag_max_crosstab = pd.crosstab(index=earthquakes.tsunami, columns=earthquakes.magType, values=earthquakes.mag, aggfunc='max')
mag_max_crosstab

magType   mb  mb_lg    md   mh   ml  ms_20    mw  mwb  mwr  mww
tsunami
0        5.6    3.5  4.11  1.1  4.2    NaN  3.83  5.8  4.8  6.0
1        6.1    NaN   NaN  NaN  5.1    5.7  4.41  NaN  NaN  7.5

Exercise 6.

Create a pivot table of the FAANG data that compares the stocks. Put the ticker in the rows and show the averages of the OHLC and volume traded data.

In [59]:
faang_data = pd.read_csv('faang.csv')

faang_data.head() #checked for headings in data

,ticker,date,high,low,open,close,volume
0,FB,2018-01-02,181.580002,177.550003,177.679993,181.419998,18151900.0
1,FB,2018-01-03,184.779999,181.330002,181.880005,184.669998,16886600.0
2,FB,2018-01-04,186.210007,184.100006,184.899994,184.330002,13880900.0
3,FB,2018-01-05,186.899994,184.929993,185.589996,186.850006,13574500.0
4,FB,2018-01-08,188.899994,186.330002,187.199997,188.279999,17994700.0

In [60]:
#creating pivot table with ticker as rows showing the averages
faang_pivot = faang_data.pivot_table(index='ticker', values=['open','high','low','close','volume'], aggfunc='mean')
#reorganizing the order to be OHLC and volume
faang_pivot = faang_pivot[['open','high','low','close','volume']]
faang_pivot

               open         high          low        close        volume
ticker
AAPL      47.277859    47.748526    46.795877    47.263357  1.360803e+08
AMZN    1644.072709  1662.839839  1619.840519  1641.726176  5.648994e+06
FB       171.472948   173.613347   169.303148   171.510956  2.765860e+07
GOOG    1113.554101  1125.777606  1101.001658  1113.225134  1.741965e+06
NFLX     319.620558   325.219322   313.187330   319.290319  1.146962e+07

Exercise 7.

Calculate the z-scores for each numeric column of Amazon’s data (ticker is AMZN) in Q4 2018 using apply().

In [61]:
#importing zscore from scipy.stats
#z-score = (value-mean)/std
from scipy.stats import zscore

#filtering data for Amazon and Q4 2018
amzn_q4 = faang_data[(faang_data.ticker == 'AMZN') & (faang_data.date >= '2018-10-01') & (faang_data.date <= '2018-12-31')].copy()

amzn_q4.head() #checked the data header

,ticker,date,high,low,open,close,volume
690,AMZN,2018-10-01,2033.189941,2003.599976,2021.989990,2004.359985,3460500.0
691,AMZN,2018-10-02,2013.390015,1965.770020,1999.989990,1971.310059,5400700.0
692,AMZN,2018-10-03,1989.699951,1949.810059,1981.699951,1952.760010,5253100.0
693,AMZN,2018-10-04,1956.000000,1896.569946,1949.000000,1909.420044,7257000.0
694,AMZN,2018-10-05,1929.079956,1862.829956,1917.989990,1889.650024,6822300.0

In [62]:
#using only the columns that include 'number'
amzn_zscores = amzn_q4.select_dtypes(include='number').apply(zscore)

#print out the data header
amzn_zscores.head()

         high       low      open     close    volume
690  2.387026  2.522211  2.356591  2.405011 -1.643506
691  2.245193  2.265485  2.208392  2.172347 -0.868802
692  2.075493  2.157176  2.085185  2.041758 -0.927738
693  1.834088  1.795871  1.864908  1.736654 -0.127599
694  1.641251  1.566901  1.656015  1.597477 -0.301170

#Exercise 10.

The European Centre for Disease Prevention and Control (ECDC) provides an open dataset on COVID-19 cases called daily number of new reported cases of COVID-19 by country worldwide. This dataset is updated daily, but we will use a snapshot that contains data through September 18, 2020. Complete the following tasks to practice the skills you've learned up to this point in the book:



Prepare the data

Read in the data in the covid19_cases.csv file.

Create a date column by parsing the dateRep column into a datetime.

Set the date column as the index.

Use the replace() method to update all occurrences of United_States_of_America and United_Kingdom to USA and UK, respectively.
Sort the index.

For the five countries with the most cases (cumulative), find the day with the largest number of cases.

Find the 7-day average change in COVID-19 cases for the last week in the data for the five countries with the most cases.

Find the first date that each country other than China had cases.

Rank the countries by cumulative cases using percentiles.

In [63]:
# Reading in data
Covid_df = pd.read_csv('covid19_cases.csv')
Covid_df.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
0,19/09/2020,19,9,2020,47,1,Afghanistan,AF,AFG,38041757.0,Asia,1.616645
1,18/09/2020,18,9,2020,0,0,Afghanistan,AF,AFG,38041757.0,Asia,1.535155
2,17/09/2020,17,9,2020,17,0,Afghanistan,AF,AFG,38041757.0,Asia,1.653446
3,16/09/2020,16,9,2020,40,10,Afghanistan,AF,AFG,38041757.0,Asia,1.708649
4,15/09/2020,15,9,2020,99,6,Afghanistan,AF,AFG,38041757.0,Asia,1.627159

In [64]:
# Parsing dateRep into datetime and setting it as index
Covid_df['date'] = pd.to_datetime(Covid_df['dateRep'], format = '%d/%m/%Y')
Covid_df.set_index('date', inplace=True)

#Using replace() to update country names
Covid_df['countriesAndTerritories'] = Covid_df['countriesAndTerritories'].replace({
    'United_States_of_America': 'USA',
    'United_Kingdom': 'UK'})

# Sorting the index
Covid_df.sort_index(inplace=True)
Covid_df.head()

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
date,,,,,,,,,,,,
2019-12-31,31/12/2019,31,12,2019,0,0,Belgium,BE,BEL,11455519.0,Europe,NaN
2019-12-31,31/12/2019,31,12,2019,0,0,Mexico,MX,MEX,127575529.0,America,NaN
2019-12-31,31/12/2019,31,12,2019,0,0,Ecuador,EC,ECU,17373657.0,America,NaN
2019-12-31,31/12/2019,31,12,2019,0,0,Russia,RU,RUS,145872260.0,Europe,NaN
2019-12-31,31/12/2019,31,12,2019,0,0,Netherlands,NL,NLD,17282163.0,Europe,NaN

In [65]:
#Finding the five countries with the most cases (cumulative)
top_5_countries  = Covid_df.groupby('countriesAndTerritories')['cases'].sum().nlargest(5).index.tolist()
top_5_countries

['USA', 'India', 'Brazil', 'Russia', 'Peru']

In [66]:
# finding the day with the largest number of cases for these 5 countries.
max_cases_day = Covid_df[Covid_df['countriesAndTerritories'].isin(top_5_countries)].groupby('countriesAndTerritories')['cases'].idxmax()

print(max_cases_day)

countriesAndTerritories
Brazil   2020-07-30
India    2020-09-17
Peru     2020-08-17
Russia   2020-07-18
USA      2020-07-25
Name: cases, dtype: datetime64[ns]

In [67]:
#Find the 7-day average change in COVID-19 cases for the last week in the data for the five countries with the most cases.
#Finding the last 7 days
last_date = Covid_df.index.max()
#Finding last week data
last_week = Covid_df[Covid_df['countriesAndTerritories'].isin(top_5_countries)].loc[last_date - pd.Timedelta(days=6):last_date]
avg_change = last_week.groupby('countriesAndTerritories')['cases'].mean()
avg_change.round(2)

countriesAndTerritories
Brazil    30431.29
India     92575.71
Peru       5677.43
Russia     5616.00
USA       39911.29
Name: cases, dtype: float64

In [68]:
#Find the first date that each country other than China had cases.
first_dates = Covid_df[(Covid_df['countriesAndTerritories'] != 'China') & (Covid_df['cases'] > 0)].groupby('countriesAndTerritories').apply(lambda x: x.index.min())
print(first_dates)

countriesAndTerritories
Afghanistan      2020-02-25
Albania          2020-03-09
Algeria          2020-02-26
Andorra          2020-03-03
Angola           2020-03-22
                    ...
Vietnam          2020-01-24
Western_Sahara   2020-04-26
Yemen            2020-04-10
Zambia           2020-03-19
Zimbabwe         2020-03-21
Length: 209, dtype: datetime64[ns]

In [69]:
#Rank the countries by cumulative cases using percentiles.
cumul_percentile = Covid_df.groupby('countriesAndTerritories')['cases'].sum()
rank_percentile = cumul_percentile.rank(pct=True).sort_values(ascending=False)
print(rank_percentile.round(4))

countriesAndTerritories
USA                            1.0000
India                          0.9952
Brazil                         0.9905
Russia                         0.9857
Peru                           0.9810
                                ...
Greenland                      0.0238
Montserrat                     0.0167
Falkland_Islands_(Malvinas)    0.0167
Holy_See                       0.0095
Anguilla                       0.0048
Name: cases, Length: 210, dtype: float64