
*  DSC530-T302 Data Exploration and Analysis (2263-1)
*  Week 3 & 4 Assignments
*  Paula Iman

# Hands-on data analysis with Pandas

# Chapter 1, Exercise 4

Run the code in the first cell of the exercises.ipynb notebook. It will give you a list of 100 values to work with for the rest of the exercises in this chapter. Be sure to treat these values as a sample of the population.

In [48]:
import random

random.seed(0)
salaries = [round(random.random()*1000000, -3) for _ in range(100)]
# Currently, this code generates a list of random values as salaries for this exercise.
print(salaries[:5])

[844000.0, 758000.0, 421000.0, 259000.0, 511000.0]

## Chapter 1, Exercise 5

Using the data from exercise 4, calculate the following statistics without importing anything from the [statistics module](https://docs.python.org/3/library/statistics.html) in the Python standard library, and then confirm your results match up to those that are obtained when using the statistics module (where possible):

Tip from instructor: You can use [Pandas](https://pandas.pydata.org/docs/getting_started/intro_tutorials/06_calculate_statistics.html) or [Numpy](https://numpy.org/doc/stable/reference/routines.statistics.html) for the initial calculation and then check against other Python library/package such as [statistics module](https://docs.python.org/3/library/statistics.html), or [SciPy Statistics](https://docs.scipy.org/doc/scipy/reference/stats.html). Part a of Exercise 5 is completed to illustrate the process for you, you can decide how to go about the other problems.

Exercise 5(a) Mean - with exmaples

In [49]:
n = len(salaries) # assigning the number of random salaries to variable n
manual_mean = sum(salaries) / n 
print(manual_mean)

585690.0

In [50]:
# Run this code to make alias to shorted the typed name
# You can do this as the 1st thing in any notebook or later, but you only need to do this once
import numpy as np
import pandas as pd

In [51]:
# Using numpy.mean
np.mean(salaries)

np.float64(585690.0)

In [52]:
# Using Pandas
# If you choose to use Pandas functions, you have to convert the list to a Series, otherwise it will give an error
salaries_series = pd.Series(salaries)
# For Pandas function, when you place a dot after a variable or other functions, it is referred to as a "method chaining" approach.
salaries_series.mean()

np.float64(585690.0)

In [53]:
# Using SciPy Statistics
from scipy import stats
stats.tmean(salaries)

np.float64(585690.0)

In [54]:
# Using the statistics module
import sys
import statistics # no need to re-run this after import
# You have to import this standard library before using its mean function
statistics.mean(salaries)

585690.0

Exercise 5(b) Median

In [55]:
# Your 1st approach - manual calculation
# Sorting the salaries list in size order
sorted_salaries = sorted(salaries)
# Since there are 100 salaries, the median is between the two middle values.
# Calculating the average of the two middle values.

manual_median = (sorted_salaries[n//2-1] + sorted_salaries[n//2]) /2
print(manual_median)

589000.0

In [56]:
# Using numpy.median
np.median(salaries)

np.float64(589000.0)

In [57]:
# Using statistics module
statistics.median(salaries)

589000.0

Exercise 5(c) Mode

Hint from textbook: Check out the [Counter class](https://docs.python.org/3/library/collections.html#collections.Counter) in the collections module of the standard library

In [58]:
# Your 1st approach: Import Counter
from collections import Counter
# Mode: Most frequent value
manual_mode = Counter(salaries).most_common(1)
print(manual_mode)

[(477000.0, 3)]

In [59]:
# Using skypy to calculate mode because Numpy does not have a built-in function to calculate mode
# Error informed that keepdims was needed.
stats.mode(salaries, keepdims=True)

ModeResult(mode=array([477000.]), count=array([3]))

In [60]:
# Using the statistics module
statistics.multimode(salaries)

[477000.0]

Exercise 5(d) Sample Variance

In [61]:
# Your 1st approach
# manual_mean is mean, and n is the number of salaries.
# Using n-1 since this represents a sample of salaries.
manual_variance = sum((x - manual_mean)**2 for x in salaries) / (n-1)
print(round(manual_variance, 2))

70664054444.44

In [62]:
# using Numpy to calculate variance
np.var(salaries)

np.float64(69957413900.0)

In [63]:
# Using the statistics module
# Using variance to calculate variance from a sample. 
statistics.variance(salaries)

70664054444.44444

Exercise 5(e) Sample Standard Deviation

In [64]:
# Your 1st approach
# using square of manual_variance
manual_std = manual_variance**0.5
print(round(manual_std, 2))

265827.11

In [65]:
# using Numpy to calculate standard deviation
salaries_std = np.std(salaries)
print(round(salaries_std, 2))

264494.64

In [66]:
# Using the statistics module
# Using stdev because variance is calculated from sample. 
statistics_std = statistics.stdev(salaries)
print(round(statistics_std, 2))

265827.11

## Chapter 1, Exercise 6

Using the data from exercise 4, calculate the following statistics using the functions in the statistics module where appropriate:

Exercise 6(a) Range

In [67]:
# Hint: there is no function called "Range". However, what does it mean to see a range of values?
# Your solution
salaries_range = max(salaries) - min(salaries)
print(salaries_range)

995000.0

To see the range of values means the difference between the maximum value and the minimum value.

Exercise 6(b) Coefficient of Variation

In [68]:
# Hint: Coefficient of Variation (CV) is defined as the ratio of standard deviation to the mean in Hands-on Data Analysis with Pandas.
# Your solution
# Using previous calculations for std and mean. STD is calculated for sample of 100 salaries.
salaries_std = statistics.pstdev(salaries)
salaries_mean = stats.tmean(salaries)
CV = salaries_std / salaries_mean
print(f"Coefficient of variation (CV) is {round(CV, 4)}")

Coefficient of variation (CV) is 0.4516

Exercise 6(c) Interquartile Range

In [69]:
# Hint: Interquartile range (IQR) is presented as the difference between the 75% and 25% quantiles in Chapter 1 of the Practical Statistics for Data Scientists Textbook
# OR you can find the values in each quartile and then subtract Quantile 3 with Quantile 1, as in Chapter 1 of Hands-on Data Analysis with Pandas
# Your solution
# Sorting the salaries
sorted_salaries = sorted(salaries)
# Finding values of 75% and 25%. Since the count starts from a 0 index, the 25th percentile is between the 24th and 25th index 
# and the 75th percentile is between 74th and 75th index.
q1 = (sorted_salaries[24] + sorted_salaries[25])/ 2
q3 = (sorted_salaries[74] + sorted_salaries[75])/ 2
IQR = q3 - q1
print(f"Interquartile range (IQR) is {IQR}")

Interquartile range (IQR) is 417500.0

Exercise 6(d) Quartile coefficient of dispersion

In [70]:
# Once you determined the 1st and 3rd quantile values from 6(c), you can use it for this calculation
# Refer to the Quartile coefficient of dispersion formula in Chapter 1 of Hands-on Data Analysis with Pandas
# Your solution
# Quartile coefficient of dispersion (QCD) formula is (Q3-Q1)/(Q3+Q1)
print(f" 1st Quartile is {q1}")
print(f" 3rd Quartile is {q3}")
QCD = (q3 - q1)/ (q3 + q1)
print(f" Quartile coefficient of disperion (QCD) is {round(QCD,4)}")

 1st Quartile is 402000.0
 3rd Quartile is 819500.0
 Quartile coefficient of disperion (QCD) is 0.3418

## Chapter 1, Exercise 7

Scale the data created in exercise 4 using the following strategies:

Exercise 7(a) Min-max Scaling (Normalizing)

In [71]:
# Refer to the Scaling data section of your reading in Chapter 1 of Hands-on Data Analysis with Pandas
# You can calculate this value by following the formula in the textbook or see the example in the solution
# You can also test out the scikit-learn function "MinMaxScaler", which requires transforming the data into a 2D array before applying the scaler. 
# This is a common approach in machine learning.
# Your solution

In [72]:
# Refer to the Scaling data section of your reading in Chapter 1 of Hands-on Data Analysis with Pandas
# You can calculate this value by following the formula in the textbook or see the example in the solution
# You can also test out the z-score method in Scipy Stats (2D array is needed)
# Your solution
# current salaries are 1D sequence
# np.array(salaries).shape, result is (100,). 
# transforming to 2D shape. Manual formula: (x - min) / (max - min)
salaries_2D = np.array(salaries).reshape(-1,1)
np.array(salaries_2D).shape

(100, 1)

In [73]:
# importing MinMaxScaler 
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
# Tilt and transform salaries
scaled_salaries = scaler.fit_transform(salaries_2D)
print(scaled_salaries[:5])

[[0.84723618]
 [0.76080402]
 [0.42211055]
 [0.25929648]
 [0.51256281]]

Exercise 7(b) Standardizing

In [74]:
# # using StandardScaler from sklearn
from sklearn.preprocessing import StandardScaler
# initialize the standard scaler
std_scaler = StandardScaler()
# formula to use: z = 9x-mean) / std.dev
standardized_salaries = std_scaler.fit_transform(salaries_2D)

# printing out mean and standard deviation
print(f"Mean : {standardized_salaries.mean():.2f}")
print(f"Standard deviation : {standardized_salaries.std():.2f}")
print(standardized_salaries[:5])

Mean : 0.00
Standard deviation : 1.00
[[ 0.97661715]
 [ 0.65146878]
 [-0.62265912]
 [-1.23514791]
 [-0.28238758]]

## Chapter 1, Exercise 8

Using the scaled data from exercise 7, calculate the following:

Note. There is some preparation work to create the normalized (scaled) vs. standardized dataset before calculating covariance.

In [75]:
# If you did not setup a scaled data or standardized data with z-score approach, you can use the following codes.
# Scaled data aka normalized data
from sklearn.preprocessing import MinMaxScaler
# Make an array of salaries
salaries_array = np.array(salaries)
# Reshape the data to 2D (one feature)
salaries_2d = salaries_array.reshape(-1, 1)
# Scaled the data
scaler = MinMaxScaler()
scaler.fit(salaries_2d)
# Optionally, transform the data. scaled_salaries in the scaled data for use in next step
scaled_salaries = scaler.transform(salaries_2d)
# Preview the first 10 values. Noticed the double [] that shows the 2D shape
scaled_salaries[:10]

array([[0.84723618],
       [0.76080402],
       [0.42211055],
       [0.25929648],
       [0.51256281],
       [0.40603015],
       [0.78693467],
       [0.30351759],
       [0.47839196],
       [0.58492462]])

In [76]:
# This will print the shape if you would like to check
scaled_salaries.shape

(100, 1)

In [77]:
# Standardized version of the salary data (z-score)
from scipy import stats
# Assign a new variable `standardized_salary` to store the standarized data
standardized_salary = stats.zscore(salaries_array)
# Preview the first 10 values. This is a 1 dimension object
standardized_salary[:10]

array([ 0.97661715,  0.65146878, -0.62265912, -1.23514791, -0.28238758,
       -0.68315184,  0.74976945, -1.06879293, -0.41093461, -0.01017034])

In [78]:
# This will print the shape if you would like to check
standardized_salary.shape

(100,)

Exercise 8(a) The covariance between the standardized and normalized data

In [79]:
# Using numpy to calculate covariance
# When the (normalized) scaled_salaries varaible was created, it was created as a 2D array.
# We will have to 'flatten' it to match the shape of the standardized_salary before calculation.
scaled_salaries = np.array(scaled_salaries).flatten()
print(scaled_salaries[:10])

[0.84723618 0.76080402 0.42211055 0.25929648 0.51256281 0.40603015
 0.78693467 0.30351759 0.47839196 0.58492462]

In [80]:
# Calculating the covariance
cov_calculated = np.cov(scaled_salaries, standardized_salary)
print(cov_calculated)

[[0.07137603 0.26850885]
 [0.26850885 1.01010101]]

In [81]:
# Covariance calculated with the statistics module
statistics.covariance(scaled_salaries, standardized_salary)

np.float64(0.2685088459449036)

Exercise 8(b) The Pearson correlation coefficient between the standardized and normalized data (this is actually 1, but due to rounding along the way, the result will be slightly less)

In [82]:
# Correlation can be calculated with statistics module
statistics.correlation(scaled_salaries, standardized_salary)
# The result is 1 because we are checking relationship of the same data in different format.

np.float64(1.0000000000000002)

Note. Getting a correlation of 1 is often very rare, but in this case, we are basically using the same raw data and simply normalized it (force values to 0,1 range) or standardized it (force the data to centered around zero and then deviate from zero) to put it on a common scale. It will not change the strength or direction of the relationship between 2 variables.

# Chapter 2

In [83]:
# The ipynb file is in ch_02 folder with the data folder
import numpy as np
import pandas as pd

df = pd.read_csv('data/parsed.csv')

df.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,status,time,title,tsunami,type,types,tz,updated,url,parsed_place
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...,California
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...,California
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...,California
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...,California
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...,California

## Chapter 2, Exercise 1

Find the 95th percentile of earthquake magnitude in Japan using the mb magnitude type.

In [84]:
japan_mb_magnitudes = df[
    (df['magType'] == 'mb') &
     (df['place'].str.contains('Japan', case=False, na=False))
]['mag']

# Take the 95th percentile (0.95 quantile) of the filtered magnitudes
percentile_95 = japan_mb_magnitudes.quantile(0.95)

print(percentile_95)

4.9

## Chapter 2, Exercise 2

Find the percentage of earthquakes in Indonesia that were coupled with tsunamis.

In [85]:
indonesia_df = df[
    df['parsed_place'].str.contains('Indonesia', case=False, na=False)
    ]

# Finding the number of rows with shape
total_indonesia_events = indonesia_df.shape[0]

print(f"Indonesia had {total_indonesia_events} earthquakes")

# Finding the tsunami amount in Indonesia 'tsunami '==1 using the sum of all events. No even is 0
tsunami_events = indonesia_df['tsunami'].sum()

print(f"Out of {total_indonesia_events} earthquakes {tsunami_events} included tsunami.")

# Calculating percentage
percentage = (tsunami_events / total_indonesia_events) * 100


print(f"Percentage of earthquakes with tsunami in Indonesia: {round(percentage,2)}")

Indonesia had 147 earthquakes
Out of 147 earthquakes 34 included tsunami.
Percentage of earthquakes with tsunami in Indonesia: 23.13

## Chapter 2, Exercise 3

Calculate summary statistics for earthquakes in Nevada.

In [86]:
nevada_df = df[
df['parsed_place'].str.contains('Nevada', case=False, na=False)
]
nevada_df.describe()

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,15.000000,681.000000,15.000000,681.000000,681.000000,1.00,681.000000,681.000000,681.000000,6.810000e+02,681.0,681.0,6.810000e+02
mean,2.440000,0.166199,2.400000,153.668120,0.500073,2.84,12.618209,0.151986,10.970631,1.538314e+12,0.0,-480.0,1.538402e+12
std,0.501142,0.166228,4.626013,68.735302,0.696710,NaN,9.866963,0.084662,19.607150,5.965637e+08,0.0,0.0,6.010951e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537307e+12
25%,2.000000,0.053000,1.000000,97.380000,-0.100000,2.84,6.000000,0.106900,0.000000,1.537854e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.112000,1.000000,149.140000,0.400000,2.84,10.000000,0.146300,2.000000,1.538280e+12,0.0,-480.0,1.538428e+12
75%,2.900000,0.233000,1.000000,199.720000,0.900000,2.84,16.000000,0.187100,12.000000,1.538821e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.863400,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

## Chapter 2, Exercise 4

Add a column indicating whether the earthquake happened in a country or US state that is on the Ring of Fire. Use Alaska, Antarctica (look for Antarctic), Bolivia, California, Canada, Chile, Costa Rica, Ecuador, Fiji, Guatemala, Indonesia, Japan, Kermadec Islands, Mexico (be careful not to select New Mexico), New Zealand, Peru, Philippines, Russia, Taiwan, Tonga, and Washington.

In [87]:
# Define list of Ring of Fire locations
# Antarctica is Antarctic and New Mexico is excluded '(?<!New )Mexico'

ring_of_fire_locations = [
   'Alaska', 'Antarctic', 'Bolivia', 'California', 'Canada', 'Chile', 'Costa Rica', 'Ecuador', 'Fiji', 'Guatemala', 'Indonesia', 'Japan',
    'Kermadec Islands', '(?<!New )Mexico', 'New Zealand', 'Peru', 'Philippines', 'Russia', 'Taiwan', 'Tonga', 'Washington'
]

# Create the regex pattern joining the list with the OR operator (|)
regex_pattern = '|'.join(ring_of_fire_locations)

# Create new df with ring of fire
# Using regex=True and na=False to handle missing values and ensure regex matching
df_with_ring_of_fire = df.assign(
    in_ring_of_fire=df['parsed_place'].str.contains(
        regex_pattern,
        case=False,  # case-insensitive matching
        na=False,
        regex=True  # use regex matching
    )
)

print(df_with_ring_of_fire[['parsed_place', 'in_ring_of_fire']].head())

  parsed_place  in_ring_of_fire
0   California             True
1   California             True
2   California             True
3   California             True
4   California             True

## Chapter 2, Exercise 5

Calculate the number of earthquakes in the Ring of Fire locations and the number outside of them.

In [88]:
ring_of_fire_count = df_with_ring_of_fire['in_ring_of_fire'].sum()
not_in_ring_of_fire = (~df_with_ring_of_fire['in_ring_of_fire']).sum()

print(f"\nTotal Earthquakes in Ring of Fire locations: {ring_of_fire_count}")
print(f"\nTotal Earthquakes not in Ring of Fire locations: {not_in_ring_of_fire}")

Total Earthquakes in Ring of Fire locations: 7188

Total Earthquakes not in Ring of Fire locations: 2144

## Chapter 2, Exercise 6

Find the tsunami count along the Ring of Fire.

In [89]:
tsunami_count = df_with_ring_of_fire[
df_with_ring_of_fire['in_ring_of_fire']
]['tsunami'].sum()
print(f"\nAmount of tsunamis around Ring of Fire: {tsunami_count}")

Amount of tsunamis around Ring of Fire: 45