Using the data/parsed.csv file and the material fromthis chapter, complete the following exercise to practis your pandas skills:

In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv('data/parsed.csv')

df.head()

,alert,cdi,code,detail,dmin,felt,gap,ids,mag,magType,...,status,time,title,tsunami,type,types,tz,updated,url,parsed_place
0,NaN,NaN,37389218,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.008693,NaN,85.0,",ci37389218,",1.35,ml,...,automatic,1539475168010,"M 1.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475395144,https://earthquake.usgs.gov/earthquakes/eventp...,California
1,NaN,NaN,37389202,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.020030,NaN,79.0,",ci37389202,",1.29,ml,...,automatic,1539475129610,"M 1.3 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475253925,https://earthquake.usgs.gov/earthquakes/eventp...,California
2,NaN,4.4,37389194,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.021370,28.0,21.0,",ci37389194,",3.42,ml,...,automatic,1539475062610,"M 3.4 - 8km NE of Aguanga, CA",0,earthquake,",dyfi,focal-mechanism,geoserve,nearby-cities,o...",-480.0,1539536756176,https://earthquake.usgs.gov/earthquakes/eventp...,California
3,NaN,NaN,37389186,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.026180,NaN,39.0,",ci37389186,",0.44,ml,...,automatic,1539474978070,"M 0.4 - 9km NE of Aguanga, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,",-480.0,1539475196167,https://earthquake.usgs.gov/earthquakes/eventp...,California
4,NaN,NaN,73096941,https://earthquake.usgs.gov/fdsnws/event/1/que...,0.077990,NaN,192.0,",nc73096941,",2.16,md,...,automatic,1539474716050,"M 2.2 - 10km NW of Avenal, CA",0,earthquake,",geoserve,nearby-cities,origin,phase-data,scit...",-480.0,1539477547926,https://earthquake.usgs.gov/earthquakes/eventp...,California

1. Find the 95th percentile of earthquake magnitude in Japan using 'mb' magnitude type

In [3]:
# filter for 'mb' magnitude type and location containing 'Japan'
# the .str.contains('Japan', case=Talse) ensure the filter is case insensitive
# na=False is included to handle any potential missing 'place' values

japan_mb_magnitudes = df[
    (df['magType'] == 'mb') &
     (df['place'].str.contains('Japan', case=False, na=False))
]['mag']

# Take the 95th percentile (0.95 quantile) of the filtered magnitudes
percentile_95 = japan_mb_magnitudes.quantile(0.95)

print(f"The 95th percentile of 'mb' magnitude in Japan is: {percentile_95}")

The 95th percentile of 'mb' magnitude in Japan is: 4.9

2. Find the percentage of earthquakes in Indonesia that were coupled with tsunamis.

In [4]:
# filter the DataFrame for earthquakes in Indonesia
# the. str.contains() method checks if 'Indonesia" is in the place string
# Case=False insensitive for case

indonesia_df = df[
    df['parsed_place'].str.contains('Indonesia', case=False, na=False)
    ]

# Finding the number of rows with shape
total_indonesia_events = indonesia_df.shape[0]

print(f"Indonesia had {total_indonesia_events} earthquakes")

# Finding the tsunami amount in Indonesia 'tsunami '==1 using the sum of all events. No even is 0
tsunami_events = indonesia_df['tsunami'].sum()

print(f"Out of {total_indonesia_events} earthquakes {tsunami_events} included tsunami.")

# Calculating percentage
percentage = (tsunami_events / total_indonesia_events) * 100


print(f"Percentage of earthquakes with tsunami in Indonesia: {round(percentage,2)}")

Indonesia had 147 earthquakes
Out of 147 earthquakes 34 included tsunami.
Percentage of earthquakes with tsunami in Indonesia: 23.13

3. Calculate summary statistics for earthquakes in Nevada.

In [5]:
# Filter for earthquakes in Nevada

nevada_df = df[
df['parsed_place'].str.contains('Nevada', case=False, na=False)
]
# calculate summary statistics for 'mag' column 
nevada_mag_stats = nevada_df['mag'].describe()
print(nevada_mag_stats)

nevada_df.describe()

count    681.000000
mean       0.500073
std        0.696710
min       -0.500000
25%       -0.100000
50%        0.400000
75%        0.900000
max        2.900000
Name: mag, dtype: float64

,cdi,dmin,felt,gap,mag,mmi,nst,rms,sig,time,tsunami,tz,updated
count,15.000000,681.000000,15.000000,681.000000,681.000000,1.00,681.000000,681.000000,681.000000,6.810000e+02,681.0,681.0,6.810000e+02
mean,2.440000,0.166199,2.400000,153.668120,0.500073,2.84,12.618209,0.151986,10.970631,1.538314e+12,0.0,-480.0,1.538402e+12
std,0.501142,0.166228,4.626013,68.735302,0.696710,NaN,9.866963,0.084662,19.607150,5.965637e+08,0.0,0.0,6.010951e+08
min,2.000000,0.001000,1.000000,29.140000,-0.500000,2.84,3.000000,0.000500,0.000000,1.537247e+12,0.0,-480.0,1.537307e+12
25%,2.000000,0.053000,1.000000,97.380000,-0.100000,2.84,6.000000,0.106900,0.000000,1.537854e+12,0.0,-480.0,1.537928e+12
50%,2.200000,0.112000,1.000000,149.140000,0.400000,2.84,10.000000,0.146300,2.000000,1.538280e+12,0.0,-480.0,1.538428e+12
75%,2.900000,0.233000,1.000000,199.720000,0.900000,2.84,16.000000,0.187100,12.000000,1.538821e+12,0.0,-480.0,1.538878e+12
max,3.300000,1.414000,19.000000,355.910000,2.900000,2.84,61.000000,0.863400,129.000000,1.539461e+12,0.0,-480.0,1.539483e+12

4. Add a column indicating whether the earthquake happened in a country or US state that is on the Ring of Fire. Use Alaska, Antarctica (look for Antarctic), Bolivia, California, Canada, Chile, Costa Rica, Ecuador, Fiji, Guatemala, Indonesia, Japan, Kermadec Islands, Mexico (be careful not to select New Mexico), New Zealand, Peru, Philippines, Russia, Taiwan, Tonga, and Washington.

In [9]:
# Define list of Ring of Fire locations
# Antarctica is Antarctic and New Mexico is excluded '(?<!New )Mexico'

ring_of_fire_locations = [
   'Alaska', 'Antarctic', 'Bolivia', 'California', 'Canada', 'Chile', 'Costa Rica', 'Ecuador', 'Fiji', 'Guatemala', 'Indonesia', 'Japan',
    'Kermadec Islands', '(?<!New )Mexico', 'New Zealand', 'Peru', 'Philippines', 'Russia', 'Taiwan', 'Tonga', 'Washington'
]

# Create the regex pattern joining the list with the OR operator (|)
regex_pattern = '|'.join(ring_of_fire_locations)

# Create new df with ring of fire
# Using regex=True and na=False to handle missing values and ensure regex matching
df_with_ring_of_fire = df.assign(
    in_ring_of_fire=df['parsed_place'].str.contains(
        regex_pattern,
        case=False,  # case-insensitive matching
        na=False,
        regex=True  # use regex matching
    )
)

print(df_with_ring_of_fire[['parsed_place', 'in_ring_of_fire']].head())

# Creating sample
sample_df = df_with_ring_of_fire[['title', 'parsed_place', 'in_ring_of_fire']].sample(5)
print(sample_df)

  parsed_place  in_ring_of_fire
0   California             True
1   California             True
2   California             True
3   California             True
4   California             True
                                          title parsed_place  in_ring_of_fire
3678  M 1.6 - 99km NW of Arctic Village, Alaska       Alaska             True
511              M 1.6 - 12km SSE of Corona, CA   California             True
8618  M 1.1 - 81km ENE of Cape Yakataga, Alaska       Alaska             True
8597       M 1.7 - 81km NW of Talkeetna, Alaska       Alaska             True
5702  M 1.6 - 31km SW of Tanaga Volcano, Alaska       Alaska             True

5. Calculate the number of earthquakes in the Ring of Fire locations and the number outside of them.

In [10]:
# print out the total count of Ring of Fire earthquakes
ring_of_fire_count = df_with_ring_of_fire['in_ring_of_fire'].sum()
not_in_ring_of_fire = (~df_with_ring_of_fire['in_ring_of_fire']).sum()
total_records = len(df_with_ring_of_fire)
print(f"\nTotal Earthquake locations: {total_records}")
print(f"\nTotal Earthquakes in Ring of Fire locations: {ring_of_fire_count}")
print(f"\nTotal Earthquakes not in Ring of Fire locations: {not_in_ring_of_fire}")

Total Earthquake locations: 9332

Total Earthquakes in Ring of Fire locations: 7188

Total Earthquakes not in Ring of Fire locations: 2144

6. Find tsunami count at ring of fire

In [8]:
tsunami_count = df_with_ring_of_fire[
df_with_ring_of_fire['in_ring_of_fire']
]['tsunami'].sum()
print(f"\nAmount of tsunamis around Ring of Fire: {tsunami_count}")

Amount of tsunamis around Ring of Fire: 45