In [1]:
import numpy as np 

import pandas as pd 

import matplotlib.pyplot as plt 

df = pd.read_excel("../datasets/Sample - Superstore.xls") 

df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [2]:
df_1 = df[['Customer Name','State','Sales','Profit']].sample(n=4) 

df_2 = df[['Customer Name','State','Sales','Profit']].sample(n=4) 

df_3 = df[['Customer Name','State','Sales','Profit']].sample(n=4)

In [3]:
df_cat1 = pd.concat([df_1,df_2,df_3], axis=0) 

df_cat1

         Customer Name           State     Sales    Profit
7621   Richard Bierner      California   725.344   54.4008
9375     Ashley Jarboe      California    50.000   10.5000
8410     Odella Nelson  North Carolina   630.024 -199.5076
6735    Brian Thompson      California   113.760   44.3664
6287        Ed Braxton      California   502.488  -87.9354
4398          John Lee    Pennsylvania    69.008   12.0764
9357  Jonathan Doherty        New York    43.120   15.0920
2357    Christine Phan        New York  1579.746 -447.5947
6985      Joseph Airdo        Michigan    29.520   14.4648
8943       Scot Wooten        Illinois   239.358  -47.8716
9981   Ted Butterfield            Ohio    16.520    5.3690
8937     Paul Gonzalez      California   135.984   16.9980

In [4]:
df_cat2 = pd.concat([df_1,df_2,df_3], axis=1) 

df_cat2

,Customer Name,State,Sales,Profit,Customer Name,State,Sales,Profit,Customer Name,State,Sales,Profit
7621,Richard Bierner,California,725.344,54.4008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9375,Ashley Jarboe,California,50.000,10.5000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8410,Odella Nelson,North Carolina,630.024,-199.5076,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6735,Brian Thompson,California,113.760,44.3664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6287,NaN,NaN,NaN,NaN,Ed Braxton,California,502.488,-87.9354,NaN,NaN,NaN,NaN
4398,NaN,NaN,NaN,NaN,John Lee,Pennsylvania,69.008,12.0764,NaN,NaN,NaN,NaN
9357,NaN,NaN,NaN,NaN,Jonathan Doherty,New York,43.120,15.0920,NaN,NaN,NaN,NaN
2357,NaN,NaN,NaN,NaN,Christine Phan,New York,1579.746,-447.5947,NaN,NaN,NaN,NaN
6985,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Joseph Airdo,Michigan,29.520,14.4648
8943,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Scot Wooten,Illinois,239.358,-47.8716
9981,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Ted Butterfield,Ohio,16.520,5.3690
8937,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Paul Gonzalez,California,135.984,16.9980