In [6]:
import numpy as np 

import pandas as pd 

import matplotlib.pyplot as plt 

df = pd.read_excel("../datasets/Sample - Superstore.xls") 
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [7]:
df_subset = df.loc[[i for i in range (10)],['Ship Mode','State','Sales']] 
df_subset

        Ship Mode       State     Sales
0    Second Class    Kentucky  261.9600
1    Second Class    Kentucky  731.9400
2    Second Class  California   14.6200
3  Standard Class     Florida  957.5775
4  Standard Class     Florida   22.3680
5  Standard Class  California   48.8600
6  Standard Class  California    7.2800
7  Standard Class  California  907.1520
8  Standard Class  California   18.5040
9  Standard Class  California  114.9000

In [27]:
byState = df_subset.groupby('State')
byState

In [34]:
print("\nGrouping by 'State' column and listing mean sales\n",'-'*50, sep='') 

byState.mean(numeric_only=True)

Grouping by 'State' column and listing mean sales
--------------------------------------------------

                 Sales
State
California  185.219333
Florida     489.972750
Kentucky    496.950000

In [38]:
print("\nGrouping by 'State' column and listing total sum of sales\n",'-'*50, sep='') 
byState.sum()

Grouping by 'State' column and listing total sum of sales
--------------------------------------------------

                                                    Ship Mode      Sales
State
California  Second ClassStandard ClassStandard ClassStanda...  1111.3160
Florida                          Standard ClassStandard Class   979.9455
Kentucky                             Second ClassSecond Class   993.9000

In [39]:
pd.DataFrame(byState.describe().loc['California'])

             California
Sales count    6.000000
      mean   185.219333
      std    355.889307
      min      7.280000
      25%     15.591000
      50%     33.682000
      75%     98.390000
      max    907.152000

In [40]:
df_subset.groupby('Ship Mode').describe().loc[['Second Class','Standard Class']]

               Sales                                                           \
               count        mean         std    min      25%     50%      75%
Ship Mode
Second Class     3.0  336.173333  364.373037  14.62  138.290  261.96  496.950
Standard Class   7.0  296.663071  435.947552   7.28   20.436   48.86  511.026


                     max
Ship Mode
Second Class    731.9400
Standard Class  957.5775

In [41]:
byStateCity = df.groupby(['State','City'])
byStateCity.describe()['Sales']

                      count         mean       min        25%       50%  \
State     City
Alabama   Auburn        6.0   294.471667     3.760     8.8050   182.030
          Decatur      13.0   259.601538    14.940    23.9200    44.950
          Florence      5.0   399.470000     4.980     7.2700    12.480
          Hoover        4.0   131.462500     7.160    13.3925    20.725
          Huntsville   10.0   248.437000     3.620    26.8700    81.920
...                     ...          ...       ...        ...       ...
Wisconsin Superior      9.0   144.414444     5.560    17.1200    47.400
          Waukesha      1.0    54.500000    54.500    54.5000    54.500
          Wausau        4.0    79.370000    12.390    20.0325    29.605
          West Allis    2.0   125.240000     8.520    66.8800   125.240
Wyoming   Cheyenne      1.0  1603.136000  1603.136  1603.1360  1603.136

                            75%       max         std
State     City
Alabama   Auburn       456.4075   900.080  361.914543
          Decatur      239.9200  1215.920  385.660903
          Florence     152.7600  1819.860  796.488863
          Hoover       138.7950   477.240  230.646923
          Huntsville   171.8075  1319.960  419.576667
...                         ...       ...         ...
Wisconsin Superior     125.9900   629.100  213.394065
          Waukesha      54.5000    54.500         NaN
          Wausau        88.9425   245.880  111.450605
          West Allis   183.6000   241.960  165.067007
Wyoming   Cheyenne    1603.1360  1603.136         NaN

[604 rows x 8 columns]

In [42]:
byStateCity.describe()['Sales'].loc['Georgia']

,count,mean,min,25%,50%,75%,max,std
City,,,,,,,,
Athens,8.0,215.101250,12.78,15.5625,117.445,191.4300,1049.93,346.513785
Atlanta,39.0,440.970256,2.74,14.9050,67.800,223.7750,6354.95,1134.579541
Columbus,68.0,218.309559,3.76,31.8650,69.170,294.9775,2939.93,404.271301
East Point,3.0,89.466667,27.42,51.2100,75.000,120.4900,165.98,70.403705
Macon,6.0,60.668333,7.16,34.4475,48.800,77.5900,142.40,47.597718
Marietta,7.0,419.802857,5.64,80.0100,182.670,663.4950,1263.30,535.060752
Roswell,18.0,369.573333,1.78,15.9450,104.130,337.6800,2690.97,666.660391
Sandy Springs,14.0,142.645000,5.95,15.3075,25.995,81.4200,1266.86,332.815411
Smyrna,17.0,140.606471,5.67,17.9400,119.560,167.9600,484.83,140.443873
Warner Robins,2.0,217.400000,41.86,129.6300,217.400,305.1700,392.94,248.251049
Woodstock,2.0,143.325000,14.04,78.6825,143.325,207.9675,272.61,182.836600