
*  DSC 530 Data Exploration and Analysis
*  Week 1-2 Assignments
*  Paula Iman
*  Due date 12/14/2025

# Chapter 3, Exercise 1
We want to look at data for the Facebook, Apple, Amazon, Netflix, and Google (FAANG) stocks, but we were given each as a separate CSV file (obtained using the stock_analysis package we will build in Chapter 7, Financial Analysis – Bitcoin and the Stock Market). Combine them into a single file and store the dataframe of the FAANG data as faang for the rest of the exercises:

Read in the aapl.csv, amzn.csv, fb.csv, goog.csv, and nflx.csv files.
Add a column to each dataframe, called ticker, indicating the ticker symbol it is for (Apple's is AAPL, for example); this is how you look up a stock. In this case, the filenames happen to be the ticker symbols.
Append them together into a single dataframe.
Save the result in a CSV file called faang.csv

In [78]:
# Importing all the data frames
# Assigning ticker to each data frame
import pandas as pd
aapl_df= pd.read_csv('exercises/aapl.csv').assign(ticker='AAPL')
amzn_df= pd.read_csv('exercises/amzn.csv').assign(ticker='AMZN')
fb_df= pd.read_csv('exercises/fb.csv').assign(ticker='FB')
goog_df= pd.read_csv('exercises/goog.csv').assign(ticker='GOOG')
nflx_df= pd.read_csv('exercises/nflx.csv').assign(ticker='NFLX')

# Combining the data frames into one list
all_df = [aapl_df, amzn_df, fb_df, goog_df, nflx_df]

# Using pd.concat() to append the rows of all data frames into one data frame
# Ignoring the index in each data frame and resetting it into the final FAANG data frame
faang_df = pd.concat(all_df, ignore_index=True)

# saving the result as CSV file called faang.csv
faang_df.to_csv('exercises/faang.csv', index=False)


# taking a sample of the new data frame.
faang_df.sample(n=5, ignore_index=True)

         date     high      low     open    close         volume ticker
0  2018-01-09   188.80   187.10   188.70   187.87  12,393,100.00     FB
1  2018-11-01    55.59    54.20    54.76    55.56 233,292,800.00   AAPL
2  2018-10-29   148.83   139.03   148.50   142.09  31,336,800.00     FB
3  2018-12-17 1,576.13 1,505.01 1,566.00 1,520.91   8,829,800.00   AMZN
4  2018-06-25 1,705.00 1,646.31 1,702.51 1,663.15   7,511,200.00   AMZN

# Chapter 3, Exercise 2
With faang, use type conversion to cast the values of the date column into datetimes and the volume column into integers. Then, sort by date and ticker.

In [79]:
# looking into the data faang_df data types
faang_df.dtypes

date       object
high      float64
low       float64
open      float64
close     float64
volume    float64
ticker     object
dtype: object

In [82]:
# Using conversion to cast the values of the date column into datetimes and volume as integer
faang_df = faang_df.assign(
    date=lambda x: pd.to_datetime(x.date),
    volume=lambda x: x.volume.astype('int')
)
faang_df.dtypes

date      datetime64[ns]
high             float64
low              float64
open             float64
close            float64
volume             int32
ticker            object
dtype: object

In [83]:
# Sort by date and ticker
faang_df.sort_values(
    by=['date', 'ticker'])

           date     high      low     open    close     volume ticker
0    2018-01-02    43.08    42.31    42.54    43.06  102223600   AAPL
251  2018-01-02 1,190.00 1,170.51 1,172.00 1,189.01    2694500   AMZN
502  2018-01-02   181.58   177.55   177.68   181.42   18151900     FB
753  2018-01-02 1,066.94 1,045.23 1,048.34 1,065.00    1237600   GOOG
1004 2018-01-02   201.65   195.42   196.10   201.07   10966900   NFLX
...         ...      ...      ...      ...      ...        ...    ...
250  2018-12-31    39.84    39.12    39.63    39.44  140014000   AAPL
501  2018-12-31 1,520.76 1,487.00 1,510.80 1,501.97    6954500   AMZN
752  2018-12-31   134.64   129.95   134.45   131.09   24625300     FB
1003 2018-12-31 1,052.70 1,023.59 1,050.96 1,035.61    1493300   GOOG
1254 2018-12-31   270.10   260.00   260.16   267.66   13508900   NFLX

[1255 rows x 7 columns]

# Chapter 3, Exercise 3
Find the seven rows in faang with the lowest value for volume.

In [84]:
faang_df.sort_values(by=['volume'], ascending=True, ignore_index=True).head(7)

        date     high      low     open    close  volume ticker
0 2018-07-03 1,135.82 1,100.02 1,135.82 1,102.89  679000   GOOG
1 2018-11-23 1,037.59 1,022.40 1,030.00 1,023.88  691500   GOOG
2 2018-05-24 1,080.47 1,066.15 1,079.00 1,079.24  766800   GOOG
3 2018-07-10 1,159.59 1,149.59 1,156.98 1,152.84  798400   GOOG
4 2018-08-09 1,255.54 1,246.01 1,249.90 1,249.10  848600   GOOG
5 2018-08-20 1,211.00 1,194.63 1,205.02 1,207.77  870800   GOOG
6 2018-08-22 1,211.84 1,199.00 1,200.00 1,207.33  887400   GOOG

# Chapter 3, Exercise 4
Right now, the data is somewhere between long and wide format. Use melt() to make it completely long format. Hint: date and ticker are our ID variables (they uniquely identify each row). We need to melt the rest so that we don't have separate columns for open, high, low, close, and volume.

In [86]:
# setting the format due to dollar amounts were showing in scientific notation
pd.set_option('display.float_format','{:,.2f}'.format)

# Use melt() to make it completely long format
melted_df = faang_df.melt(
    id_vars = ['date', 'ticker'], value_vars=['open', 'high', 'low', 'close', 'volume'],
    value_name= 'dollars', var_name='measure'
)

# Sorting the df by data, ticker, and measure
sorted_melted_df = melted_df.sort_values(
    ['date','ticker', 'measure']
).reset_index(drop=True)

sorted_melted_df.head(n=10)

        date ticker measure        dollars
0 2018-01-02   AAPL   close          43.06
1 2018-01-02   AAPL    high          43.08
2 2018-01-02   AAPL     low          42.31
3 2018-01-02   AAPL    open          42.54
4 2018-01-02   AAPL  volume 102,223,600.00
5 2018-01-02   AMZN   close       1,189.01
6 2018-01-02   AMZN    high       1,190.00
7 2018-01-02   AMZN     low       1,170.51
8 2018-01-02   AMZN    open       1,172.00
9 2018-01-02   AMZN  volume   2,694,500.00

# Chapter 3, Exercise 5
Suppose we found out that on July 26, 2018 there was a glitch in how the data was recorded. How should we handle this? Note that there is no coding required for this exercise.

To initiate an investigation of an anomaly, it is essential to confirm that a glitch exists and define its scope. We need to find out:
Scope of Impact: Was the anomaly present only in one ticker, or did it affect all of them?
Temporal Range: Did the glitch infect only one day, or did it also affect previous or following days?
Origin: Did the glitch originate in one of the original source data files, or did it appear during the file combination process?
If the glitch originated from one of the source data files, we have several options for correction:
Option 
1: Exclusion. We could exclude or filter out data from the affected day to avoid bias. However, losing data may negatively impact short-term analysis.
Option 
2: Imputation (Fill/Interpolation). We could use forward or backward fill, replacing the glitched value with the closing price from the previous day (e.g., July 25th) or the next day (e.g., July 27th). Interpolation is another option, which replaces the missing value by calculating the average of the surrounding values. While this allows the data to run smoothly, the replaced data will be artificial and may obscure a real-world market event that appears as a glitch.
Option 
3: External Verification. If time allows, we could seek the correct data from another verified source to replace the flawed data entirely.
In any case, it is essential to be transparent and thoroughly document the changes made to the original data. This notation should clarify the date the glitch occurred, its nature, and the specific method used to address it

# Chapter 3, Exercise 6
The European Centre for Disease Prevention and Control (ECDC) provides an open dataset on COVID-19 cases called daily number of new reported cases of COVID-19 by country worldwide. This dataset is updated daily, but we will use a snapshot that contains data from January 1, 2020 through September 18, 2020. Clean and pivot the data so that it is in wide format:

Read in the covid19_cases.csv file.
Create a date column using the data in the dateRep column and the pd.to_datetime() function.
Set the date column as the index and sort the index.
Replace all occurrences of United_States_of_America and United_Kingdom with USA and UK, respectively. Hint: the replace() method can be run on the dataframe as a whole.
Using the countriesAndTerritories column, filter the cleaned COVID-19 cases data down to Argentina, Brazil, China, Colombia, India, Italy, Mexico, Peru, Russia, Spain, Turkey, the UK, and the USA.
Pivot the data so that the index contains the dates, the columns contain the country names, and the values are the case counts (the cases column). Be sure to fill in NaN values with 0.

In [87]:
# reading in covid19_cases.csv
covid_data = pd.read_csv('exercises/covid19_cases.csv')

covid_data.head(5)

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
0,01/01/2020,1,1,2020,0,0,Lithuania,LT,LTU,"2,794,184.00",Europe,NaN
1,01/01/2020,1,1,2020,0,0,Iceland,IS,ISL,"356,991.00",Europe,NaN
2,01/01/2020,1,1,2020,0,0,Nepal,NP,NPL,"28,608,715.00",Asia,NaN
3,01/01/2020,1,1,2020,0,0,San_Marino,SM,SMR,"34,453.00",Europe,NaN
4,01/01/2020,1,1,2020,0,0,Canada,CA,CAN,"37,411,038.00",America,NaN

In [95]:
# Creating a date column using dateRep column and pd.to_datetime() function
covid_data.loc[:, 'date'] = pd.to_datetime(
    covid_data['dateRep'], 
    dayfirst=True,
)

In [96]:
# Set the 'date' column as the index and sort
covid_data = covid_data.set_index('date').sort_index()

# checking data
covid_data.head(5)

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
date,,,,,,,,,,,,
2020-01-01,01/01/2020,1,1,2020,0,0,Lithuania,LT,LTU,"2,794,184.00",Europe,NaN
2020-01-01,01/01/2020,1,1,2020,0,0,Iceland,IS,ISL,"356,991.00",Europe,NaN
2020-01-01,01/01/2020,1,1,2020,0,0,Nepal,NP,NPL,"28,608,715.00",Asia,NaN
2020-01-01,01/01/2020,1,1,2020,0,0,San_Marino,SM,SMR,"34,453.00",Europe,NaN
2020-01-01,01/01/2020,1,1,2020,0,0,Canada,CA,CAN,"37,411,038.00",America,NaN

In [97]:
#Replace all occurrences of United_States_of_America and United_Kingdom with USA and UK, respectively. Hint: the replace() method can be run on the dataframe as a whole.
replacements = {
    'United_States_of_America': 'USA',
    'United_Kingdom': 'UK'
}
covid_data = covid_data.replace(replacements, regex=False)

In [98]:
# Using the countriesAndTerritories column, filter the cleaned COVID-19 cases data down to 
# Argentina, Brazil, China, Colombia, India, Italy, Mexico, Peru, Russia, Spain, Turkey, the UK, and the USA.
filtered_covid_data = covid_data[
covid_data['countriesAndTerritories'].isin(['Argentina', 'Brazil', 'China', 'Colombia', 'India',
                                           'Italy', 'Mexico', 'Peru', 'Russia', 'Spain',
                                           'Turkey', 'UK', 'USA'])
]
filtered_covid_data[filtered_covid_data['countriesAndTerritories'] == 'UK'].head(5)

,dateRep,day,month,year,cases,deaths,countriesAndTerritories,geoId,countryterritoryCode,popData2019,continentExp,Cumulative_number_for_14_days_of_COVID-19_cases_per_100000
date,,,,,,,,,,,,
2020-01-01,01/01/2020,1,1,2020,0,0,UK,UK,GBR,"66,647,112.00",Europe,NaN
2020-01-02,02/01/2020,2,1,2020,0,0,UK,UK,GBR,"66,647,112.00",Europe,NaN
2020-01-03,03/01/2020,3,1,2020,0,0,UK,UK,GBR,"66,647,112.00",Europe,NaN
2020-01-04,04/01/2020,4,1,2020,0,0,UK,UK,GBR,"66,647,112.00",Europe,NaN
2020-01-05,05/01/2020,5,1,2020,0,0,UK,UK,GBR,"66,647,112.00",Europe,NaN

In [99]:
# Pivot the data so that the index contains the dates, the columns contain the country names, and the values are the case counts (the cases column). 
cases_by_country = filtered_covid_data.reset_index().pivot_table(
    index='date',
    columns='countriesAndTerritories',
    values='cases'
)

# Be sure to fill in NaN values with 0.
cases_by_country = cases_by_country.fillna(0)

cases_by_country.head()

countriesAndTerritories,Argentina,Brazil,China,Colombia,India,Italy,Mexico,Peru,Russia,Spain,Turkey,UK,USA
date,,,,,,,,,,,,,
2020-01-01,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2020-01-02,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2020-01-03,0.00,0.00,17.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2020-01-04,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
2020-01-05,0.00,0.00,15.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00